# Generated by Django 3.2.20 on 2023-07-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('ST', 'Standard/Basic Delivery'), ('EX', 'Expedited Delivery'), ('PR', 'Premium Delivery'), ('WG', 'White Glove/Platinum Delivery')], default='ST', max_length=2),
        ),
    ]
