# Generated by Django 3.2.20 on 2023-07-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(choices=[('Standard/Basic Delivery', 'Standard/Basic Delivery'), ('Expedited Delivery', 'Expedited Delivery'), ('Premium Delivery', 'Premium Delivery'), ('White Glove/Platinum Delivery', 'White Glove/Platinum Delivery')], default='Standard/Basic Delivery', max_length=50)),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='requested_time',
            field=models.CharField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], default='17:00', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_reserved', to='bookings.service'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('requested_date', 'requested_time', 'service')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
