# Generated by Django 3.2.20 on 2023-07-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20230728_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(choices=[('Standard/Basic Delivery', 'Standard/Basic Delivery'), ('Expedited Delivery', 'Expedited Delivery'), ('Premium Delivery', 'Premium Delivery'), ('White Glove/Platinum Delivery', 'White Glove/Platinum Delivery')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_reserved', to='bookings.service'),
        ),
    ]
