# Generated by Django 3.2.20 on 2023-07-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_reserved', to='bookings.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='Standard/Basic Delivery', max_length=50, unique=True),
        ),
    ]
